# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLCDNumber,
    QLabel, QLineEdit, QProgressBar, QPushButton,
    QSizePolicy, QTabWidget, QTextBrowser, QTextEdit,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(675, 534)
        self.textEdit = QTextEdit(Dialog)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 10, 659, 41))
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 60, 661, 461))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.frame_3 = QFrame(self.tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 230, 631, 181))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.pushButton_4 = QPushButton(self.frame_3)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 20, 111, 41))
        self.pushButton_3 = QPushButton(self.frame_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(300, 80, 111, 41))
        self.progressBar_5 = QProgressBar(self.frame_3)
        self.progressBar_5.setObjectName(u"progressBar_5")
        self.progressBar_5.setGeometry(QRect(170, 30, 118, 23))
        self.progressBar_5.setValue(0)
        self.progressBar_6 = QProgressBar(self.frame_3)
        self.progressBar_6.setObjectName(u"progressBar_6")
        self.progressBar_6.setGeometry(QRect(430, 90, 118, 23))
        self.progressBar_6.setValue(0)
        self.pushButton_32 = QPushButton(self.frame_3)
        self.pushButton_32.setObjectName(u"pushButton_32")
        self.pushButton_32.setGeometry(QRect(300, 130, 111, 31))
        self.textBrowser_3 = QTextBrowser(self.frame_3)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(20, 90, 181, 21))
        self.lcdNumber_3 = QLCDNumber(self.frame_3)
        self.lcdNumber_3.setObjectName(u"lcdNumber_3")
        self.lcdNumber_3.setGeometry(QRect(220, 90, 64, 23))
        self.frame_18 = QFrame(self.tab)
        self.frame_18.setObjectName(u"frame_18")
        self.frame_18.setGeometry(QRect(10, 10, 631, 191))
        self.frame_18.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QFrame.Shadow.Raised)
        self.label_12 = QLabel(self.frame_18)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 10, 111, 16))
        self.progressBar_26 = QProgressBar(self.frame_18)
        self.progressBar_26.setObjectName(u"progressBar_26")
        self.progressBar_26.setGeometry(QRect(300, 80, 118, 23))
        self.progressBar_26.setValue(0)
        self.pushButton_30 = QPushButton(self.frame_18)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(20, 30, 81, 31))
        self.pushButton_31 = QPushButton(self.frame_18)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.pushButton_31.setGeometry(QRect(300, 30, 111, 31))
        self.lineEditFilePath_6 = QLineEdit(self.frame_18)
        self.lineEditFilePath_6.setObjectName(u"lineEditFilePath_6")
        self.lineEditFilePath_6.setGeometry(QRect(110, 40, 113, 20))
        self.progressBar_27 = QProgressBar(self.frame_18)
        self.progressBar_27.setObjectName(u"progressBar_27")
        self.progressBar_27.setGeometry(QRect(300, 120, 118, 23))
        self.progressBar_27.setValue(0)
        self.textBrowser = QTextBrowser(self.frame_18)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(20, 80, 181, 21))
        self.textBrowser_2 = QTextBrowser(self.frame_18)
        self.textBrowser_2.setObjectName(u"textBrowser_2")
        self.textBrowser_2.setGeometry(QRect(20, 120, 181, 21))
        self.lcdNumber = QLCDNumber(self.frame_18)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(220, 80, 64, 23))
        self.lcdNumber_2 = QLCDNumber(self.frame_18)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(220, 120, 64, 23))
        self.pushButton = QPushButton(self.frame_18)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(430, 80, 75, 24))
        self.pushButton_2 = QPushButton(self.frame_18)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(430, 120, 75, 24))
        self.pushButton_5 = QPushButton(self.frame_18)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(520, 80, 75, 24))
        self.pushButton_6 = QPushButton(self.frame_18)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(520, 120, 75, 24))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.frame_9 = QFrame(self.tab_2)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(10, 230, 631, 181))
        self.frame_9.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Shadow.Raised)
        self.pushButton_10 = QPushButton(self.frame_9)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(20, 20, 111, 41))
        self.pushButton_11 = QPushButton(self.frame_9)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(300, 80, 111, 41))
        self.progressBar_12 = QProgressBar(self.frame_9)
        self.progressBar_12.setObjectName(u"progressBar_12")
        self.progressBar_12.setGeometry(QRect(170, 30, 118, 23))
        self.progressBar_12.setValue(0)
        self.progressBar_13 = QProgressBar(self.frame_9)
        self.progressBar_13.setObjectName(u"progressBar_13")
        self.progressBar_13.setGeometry(QRect(430, 90, 118, 23))
        self.progressBar_13.setValue(0)
        self.textBrowser_9 = QTextBrowser(self.frame_9)
        self.textBrowser_9.setObjectName(u"textBrowser_9")
        self.textBrowser_9.setGeometry(QRect(20, 90, 181, 21))
        self.lcdNumber_9 = QLCDNumber(self.frame_9)
        self.lcdNumber_9.setObjectName(u"lcdNumber_9")
        self.lcdNumber_9.setGeometry(QRect(220, 90, 64, 23))
        self.pushButton_33 = QPushButton(self.frame_9)
        self.pushButton_33.setObjectName(u"pushButton_33")
        self.pushButton_33.setGeometry(QRect(300, 130, 111, 31))
        self.frame_17 = QFrame(self.tab_2)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setGeometry(QRect(10, 10, 631, 181))
        self.frame_17.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QFrame.Shadow.Raised)
        self.label_11 = QLabel(self.frame_17)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 10, 111, 16))
        self.progressBar_25 = QProgressBar(self.frame_17)
        self.progressBar_25.setObjectName(u"progressBar_25")
        self.progressBar_25.setGeometry(QRect(300, 80, 118, 23))
        self.progressBar_25.setValue(0)
        self.pushButton_28 = QPushButton(self.frame_17)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.pushButton_28.setGeometry(QRect(20, 30, 81, 31))
        self.pushButton_29 = QPushButton(self.frame_17)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(300, 30, 111, 31))
        self.lineEditFilePath_5 = QLineEdit(self.frame_17)
        self.lineEditFilePath_5.setObjectName(u"lineEditFilePath_5")
        self.lineEditFilePath_5.setGeometry(QRect(110, 40, 113, 20))
        self.textBrowser_4 = QTextBrowser(self.frame_17)
        self.textBrowser_4.setObjectName(u"textBrowser_4")
        self.textBrowser_4.setGeometry(QRect(20, 80, 181, 21))
        self.lcdNumber_4 = QLCDNumber(self.frame_17)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setGeometry(QRect(220, 80, 64, 23))
        self.pushButton_7 = QPushButton(self.frame_17)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(520, 80, 75, 24))
        self.pushButton_8 = QPushButton(self.frame_17)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(430, 80, 75, 24))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.frame_10 = QFrame(self.tab_3)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(10, 230, 631, 181))
        self.frame_10.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Shadow.Raised)
        self.pushButton_12 = QPushButton(self.frame_10)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(20, 20, 111, 41))
        self.pushButton_13 = QPushButton(self.frame_10)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(300, 80, 111, 41))
        self.progressBar_14 = QProgressBar(self.frame_10)
        self.progressBar_14.setObjectName(u"progressBar_14")
        self.progressBar_14.setGeometry(QRect(170, 30, 118, 23))
        self.progressBar_14.setValue(0)
        self.progressBar_15 = QProgressBar(self.frame_10)
        self.progressBar_15.setObjectName(u"progressBar_15")
        self.progressBar_15.setGeometry(QRect(430, 90, 118, 23))
        self.progressBar_15.setValue(0)
        self.textBrowser_10 = QTextBrowser(self.frame_10)
        self.textBrowser_10.setObjectName(u"textBrowser_10")
        self.textBrowser_10.setGeometry(QRect(20, 90, 181, 21))
        self.lcdNumber_10 = QLCDNumber(self.frame_10)
        self.lcdNumber_10.setObjectName(u"lcdNumber_10")
        self.lcdNumber_10.setGeometry(QRect(220, 90, 64, 23))
        self.pushButton_34 = QPushButton(self.frame_10)
        self.pushButton_34.setObjectName(u"pushButton_34")
        self.pushButton_34.setGeometry(QRect(300, 130, 111, 31))
        self.frame_16 = QFrame(self.tab_3)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setGeometry(QRect(10, 10, 631, 181))
        self.frame_16.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Shadow.Raised)
        self.label_10 = QLabel(self.frame_16)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 10, 111, 16))
        self.progressBar_24 = QProgressBar(self.frame_16)
        self.progressBar_24.setObjectName(u"progressBar_24")
        self.progressBar_24.setGeometry(QRect(300, 80, 118, 23))
        self.progressBar_24.setValue(0)
        self.pushButton_26 = QPushButton(self.frame_16)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(20, 30, 81, 31))
        self.pushButton_27 = QPushButton(self.frame_16)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(300, 30, 111, 31))
        self.lineEditFilePath_4 = QLineEdit(self.frame_16)
        self.lineEditFilePath_4.setObjectName(u"lineEditFilePath_4")
        self.lineEditFilePath_4.setGeometry(QRect(110, 40, 113, 20))
        self.pushButton_38 = QPushButton(self.frame_16)
        self.pushButton_38.setObjectName(u"pushButton_38")
        self.pushButton_38.setGeometry(QRect(430, 80, 75, 24))
        self.pushButton_9 = QPushButton(self.frame_16)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(520, 80, 75, 24))
        self.textBrowser_5 = QTextBrowser(self.tab_3)
        self.textBrowser_5.setObjectName(u"textBrowser_5")
        self.textBrowser_5.setGeometry(QRect(30, 90, 181, 21))
        self.lcdNumber_5 = QLCDNumber(self.tab_3)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")
        self.lcdNumber_5.setGeometry(QRect(230, 90, 64, 23))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.frame_11 = QFrame(self.tab_4)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(10, 230, 631, 181))
        self.frame_11.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Shadow.Raised)
        self.pushButton_14 = QPushButton(self.frame_11)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(20, 20, 111, 41))
        self.pushButton_15 = QPushButton(self.frame_11)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(300, 80, 111, 41))
        self.progressBar_16 = QProgressBar(self.frame_11)
        self.progressBar_16.setObjectName(u"progressBar_16")
        self.progressBar_16.setGeometry(QRect(170, 30, 118, 23))
        self.progressBar_16.setValue(0)
        self.progressBar_17 = QProgressBar(self.frame_11)
        self.progressBar_17.setObjectName(u"progressBar_17")
        self.progressBar_17.setGeometry(QRect(430, 90, 118, 23))
        self.progressBar_17.setValue(0)
        self.textBrowser_11 = QTextBrowser(self.frame_11)
        self.textBrowser_11.setObjectName(u"textBrowser_11")
        self.textBrowser_11.setGeometry(QRect(20, 90, 181, 21))
        self.lcdNumber_11 = QLCDNumber(self.frame_11)
        self.lcdNumber_11.setObjectName(u"lcdNumber_11")
        self.lcdNumber_11.setGeometry(QRect(220, 90, 64, 23))
        self.pushButton_35 = QPushButton(self.frame_11)
        self.pushButton_35.setObjectName(u"pushButton_35")
        self.pushButton_35.setGeometry(QRect(300, 130, 111, 31))
        self.frame_15 = QFrame(self.tab_4)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(10, 10, 631, 181))
        self.frame_15.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Shadow.Raised)
        self.label_9 = QLabel(self.frame_15)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 10, 111, 16))
        self.progressBar_23 = QProgressBar(self.frame_15)
        self.progressBar_23.setObjectName(u"progressBar_23")
        self.progressBar_23.setGeometry(QRect(300, 80, 118, 23))
        self.progressBar_23.setValue(0)
        self.pushButton_24 = QPushButton(self.frame_15)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(20, 30, 81, 31))
        self.pushButton_25 = QPushButton(self.frame_15)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(300, 30, 111, 31))
        self.lineEditFilePath_3 = QLineEdit(self.frame_15)
        self.lineEditFilePath_3.setObjectName(u"lineEditFilePath_3")
        self.lineEditFilePath_3.setGeometry(QRect(110, 40, 113, 20))
        self.textBrowser_6 = QTextBrowser(self.frame_15)
        self.textBrowser_6.setObjectName(u"textBrowser_6")
        self.textBrowser_6.setGeometry(QRect(20, 80, 181, 21))
        self.lcdNumber_6 = QLCDNumber(self.frame_15)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")
        self.lcdNumber_6.setGeometry(QRect(220, 80, 64, 23))
        self.pushButton_39 = QPushButton(self.frame_15)
        self.pushButton_39.setObjectName(u"pushButton_39")
        self.pushButton_39.setGeometry(QRect(520, 80, 75, 24))
        self.pushButton_40 = QPushButton(self.frame_15)
        self.pushButton_40.setObjectName(u"pushButton_40")
        self.pushButton_40.setGeometry(QRect(430, 80, 75, 24))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.frame_12 = QFrame(self.tab_5)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(10, 230, 631, 181))
        self.frame_12.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Shadow.Raised)
        self.pushButton_16 = QPushButton(self.frame_12)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(20, 20, 111, 41))
        self.pushButton_17 = QPushButton(self.frame_12)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(300, 80, 111, 41))
        self.progressBar_18 = QProgressBar(self.frame_12)
        self.progressBar_18.setObjectName(u"progressBar_18")
        self.progressBar_18.setGeometry(QRect(170, 30, 118, 23))
        self.progressBar_18.setValue(0)
        self.progressBar_19 = QProgressBar(self.frame_12)
        self.progressBar_19.setObjectName(u"progressBar_19")
        self.progressBar_19.setGeometry(QRect(430, 90, 118, 23))
        self.progressBar_19.setValue(0)
        self.textBrowser_12 = QTextBrowser(self.frame_12)
        self.textBrowser_12.setObjectName(u"textBrowser_12")
        self.textBrowser_12.setGeometry(QRect(20, 90, 181, 21))
        self.lcdNumber_12 = QLCDNumber(self.frame_12)
        self.lcdNumber_12.setObjectName(u"lcdNumber_12")
        self.lcdNumber_12.setGeometry(QRect(220, 90, 64, 23))
        self.pushButton_36 = QPushButton(self.frame_12)
        self.pushButton_36.setObjectName(u"pushButton_36")
        self.pushButton_36.setGeometry(QRect(300, 130, 111, 31))
        self.frame_14 = QFrame(self.tab_5)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(10, 10, 631, 181))
        self.frame_14.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Shadow.Raised)
        self.label_8 = QLabel(self.frame_14)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 10, 111, 16))
        self.progressBar_22 = QProgressBar(self.frame_14)
        self.progressBar_22.setObjectName(u"progressBar_22")
        self.progressBar_22.setGeometry(QRect(300, 80, 118, 23))
        self.progressBar_22.setValue(0)
        self.pushButton_22 = QPushButton(self.frame_14)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(20, 30, 81, 31))
        self.pushButton_23 = QPushButton(self.frame_14)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(300, 30, 111, 31))
        self.lineEditFilePath_2 = QLineEdit(self.frame_14)
        self.lineEditFilePath_2.setObjectName(u"lineEditFilePath_2")
        self.lineEditFilePath_2.setGeometry(QRect(110, 40, 113, 20))
        self.textBrowser_7 = QTextBrowser(self.frame_14)
        self.textBrowser_7.setObjectName(u"textBrowser_7")
        self.textBrowser_7.setGeometry(QRect(20, 80, 181, 21))
        self.lcdNumber_7 = QLCDNumber(self.frame_14)
        self.lcdNumber_7.setObjectName(u"lcdNumber_7")
        self.lcdNumber_7.setGeometry(QRect(220, 80, 64, 23))
        self.pushButton_41 = QPushButton(self.frame_14)
        self.pushButton_41.setObjectName(u"pushButton_41")
        self.pushButton_41.setGeometry(QRect(520, 80, 75, 24))
        self.pushButton_42 = QPushButton(self.frame_14)
        self.pushButton_42.setObjectName(u"pushButton_42")
        self.pushButton_42.setGeometry(QRect(430, 80, 75, 24))
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.frame_8 = QFrame(self.tab_6)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 10, 631, 181))
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.label_7 = QLabel(self.frame_8)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 10, 111, 16))
        self.progressBar_11 = QProgressBar(self.frame_8)
        self.progressBar_11.setObjectName(u"progressBar_11")
        self.progressBar_11.setGeometry(QRect(300, 80, 118, 23))
        self.progressBar_11.setValue(0)
        self.pushButton_20 = QPushButton(self.frame_8)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(20, 30, 81, 31))
        self.pushButton_21 = QPushButton(self.frame_8)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(300, 30, 111, 31))
        self.lineEditFilePath = QLineEdit(self.frame_8)
        self.lineEditFilePath.setObjectName(u"lineEditFilePath")
        self.lineEditFilePath.setGeometry(QRect(110, 40, 113, 20))
        self.textBrowser_8 = QTextBrowser(self.frame_8)
        self.textBrowser_8.setObjectName(u"textBrowser_8")
        self.textBrowser_8.setGeometry(QRect(20, 80, 181, 21))
        self.lcdNumber_8 = QLCDNumber(self.frame_8)
        self.lcdNumber_8.setObjectName(u"lcdNumber_8")
        self.lcdNumber_8.setGeometry(QRect(220, 80, 64, 23))
        self.pushButton_43 = QPushButton(self.frame_8)
        self.pushButton_43.setObjectName(u"pushButton_43")
        self.pushButton_43.setGeometry(QRect(520, 80, 75, 24))
        self.pushButton_44 = QPushButton(self.frame_8)
        self.pushButton_44.setObjectName(u"pushButton_44")
        self.pushButton_44.setGeometry(QRect(430, 80, 75, 24))
        self.frame_13 = QFrame(self.tab_6)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(10, 230, 631, 181))
        self.frame_13.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Shadow.Raised)
        self.pushButton_18 = QPushButton(self.frame_13)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(20, 20, 111, 41))
        self.pushButton_19 = QPushButton(self.frame_13)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(300, 80, 111, 41))
        self.progressBar_20 = QProgressBar(self.frame_13)
        self.progressBar_20.setObjectName(u"progressBar_20")
        self.progressBar_20.setGeometry(QRect(170, 30, 118, 23))
        self.progressBar_20.setValue(0)
        self.progressBar_21 = QProgressBar(self.frame_13)
        self.progressBar_21.setObjectName(u"progressBar_21")
        self.progressBar_21.setGeometry(QRect(430, 90, 118, 23))
        self.progressBar_21.setValue(0)
        self.textBrowser_13 = QTextBrowser(self.frame_13)
        self.textBrowser_13.setObjectName(u"textBrowser_13")
        self.textBrowser_13.setGeometry(QRect(20, 90, 181, 21))
        self.lcdNumber_13 = QLCDNumber(self.frame_13)
        self.lcdNumber_13.setObjectName(u"lcdNumber_13")
        self.lcdNumber_13.setGeometry(QRect(220, 90, 64, 23))
        self.pushButton_37 = QPushButton(self.frame_13)
        self.pushButton_37.setObjectName(u"pushButton_37")
        self.pushButton_37.setGeometry(QRect(300, 130, 111, 31))
        self.tabWidget.addTab(self.tab_6, "")
        self.tabWidget.raise_()
        self.textEdit.raise_()

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.textEdit.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Welcome to PDF World!</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.tabWidget.setToolTip(QCoreApplication.translate("Dialog", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"PDF Merge", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"Download ", None))
        self.pushButton_32.setText(QCoreApplication.translate("Dialog", u"Delete File", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Upload Your File:", None))
        self.pushButton_30.setText(QCoreApplication.translate("Dialog", u"Select File", None))
        self.pushButton_31.setText(QCoreApplication.translate("Dialog", u"Upload ", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"Discard", None))
        self.pushButton_6.setText(QCoreApplication.translate("Dialog", u"Discard", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"PDF Merge", None))
        self.pushButton_10.setText(QCoreApplication.translate("Dialog", u"Word to PDF", None))
        self.pushButton_11.setText(QCoreApplication.translate("Dialog", u"Download ", None))
        self.pushButton_33.setText(QCoreApplication.translate("Dialog", u"Delete File", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Upload Your File:", None))
        self.pushButton_28.setText(QCoreApplication.translate("Dialog", u"Select File", None))
        self.pushButton_29.setText(QCoreApplication.translate("Dialog", u"Upload ", None))
        self.pushButton_7.setText(QCoreApplication.translate("Dialog", u"Discard", None))
        self.pushButton_8.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Word to PDF", None))
        self.pushButton_12.setText(QCoreApplication.translate("Dialog", u"JPG to PDF", None))
        self.pushButton_13.setText(QCoreApplication.translate("Dialog", u"Download ", None))
        self.pushButton_34.setText(QCoreApplication.translate("Dialog", u"Delete File", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Upload Your File:", None))
        self.pushButton_26.setText(QCoreApplication.translate("Dialog", u"Select File", None))
        self.pushButton_27.setText(QCoreApplication.translate("Dialog", u"Upload ", None))
        self.pushButton_38.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.pushButton_9.setText(QCoreApplication.translate("Dialog", u"Discard", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"JPG to PDF", None))
        self.pushButton_14.setText(QCoreApplication.translate("Dialog", u"PDF to Word", None))
        self.pushButton_15.setText(QCoreApplication.translate("Dialog", u"Download ", None))
        self.pushButton_35.setText(QCoreApplication.translate("Dialog", u"Delete File", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Upload Your File:", None))
        self.pushButton_24.setText(QCoreApplication.translate("Dialog", u"Select File", None))
        self.pushButton_25.setText(QCoreApplication.translate("Dialog", u"Upload ", None))
        self.pushButton_39.setText(QCoreApplication.translate("Dialog", u"Discard", None))
        self.pushButton_40.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Dialog", u"PDF to Word", None))
        self.pushButton_16.setText(QCoreApplication.translate("Dialog", u"PDF Scanning", None))
        self.pushButton_17.setText(QCoreApplication.translate("Dialog", u"Download ", None))
        self.pushButton_36.setText(QCoreApplication.translate("Dialog", u"Delete File", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Upload Your File:", None))
        self.pushButton_22.setText(QCoreApplication.translate("Dialog", u"Select File", None))
        self.pushButton_23.setText(QCoreApplication.translate("Dialog", u"Upload ", None))
        self.pushButton_41.setText(QCoreApplication.translate("Dialog", u"Discard", None))
        self.pushButton_42.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Dialog", u"PDF Scanning", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Upload Your File:", None))
        self.pushButton_20.setText(QCoreApplication.translate("Dialog", u"Select File", None))
        self.pushButton_21.setText(QCoreApplication.translate("Dialog", u"Upload ", None))
        self.pushButton_43.setText(QCoreApplication.translate("Dialog", u"Discard", None))
        self.pushButton_44.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.pushButton_18.setText(QCoreApplication.translate("Dialog", u"Photo Scanning", None))
        self.pushButton_19.setText(QCoreApplication.translate("Dialog", u"Download ", None))
        self.pushButton_37.setText(QCoreApplication.translate("Dialog", u"Delete File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("Dialog", u"Photo Scanning", None))
    # retranslateUi

